#!/usr/bin/env python3
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4
##
# mPlane Software Development Kit
# Component runtime
#
# (c) 2015 mPlane Consortium (http://www.ict-mplane.eu)
#     Author: Stefano Pentassuglia <stefano.pentassuglia@ssbprogetti.it>
#             Brian Trammell <brian@trammell.ch>
#
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
#

import mplane.component
import json
import argparse

if __name__ == "__main__":

    global args
    parser = argparse.ArgumentParser(description='mplane component runtime')
    parser.add_argument('--config', metavar='conf-file', dest='CONF',
                        help='Configuration file for the component')
    args = parser.parse_args()

    # check if conf file parameter has been inserted in the command line
    if not args.CONF:
        print('\nWARNING: missing --config, using default settings. Component may be unstable\n')
        parser.print_help()
        config = None
    else:
        # Read the configuration file
        conf_file = open(mplane.utils.search_path(args.CONF), 'r')
        config = json.load(conf_file)

    if config is None:
        component = mplane.component.InitiatorHttpComponent(config)
    else:
        if "Initiator" in config["Component"] and "Listener" in config["Component"]:
            raise ValueError("Component cannot be 'Initiator' and 'Listener' simultaneously. "
                             "Remove one of them from " + args.CONF + "")
        if "Initiator" in config["Component"]:
            component = mplane.component.InitiatorHttpComponent(config)
        elif "Listener" in config["Component"]:
            component = mplane.component.ListenerHttpComponent(config)
        else:
            print("WARNING: need either a 'Initiator' or 'Listener' object under 'Component' in " + args.CONF +
                  ". Using default settings (Initiator)")
            component = mplane.component.InitiatorHttpComponent(config)
